ScrumTool/protected/models/Project.php
<?php

/**
 * This is the model class for table "project".
 *
 * The followings are the available columns in table 'project':
 * @property integer $id
 * @property string $name
 * @property integer $active
 * @property integer $team_id
 * @property integer $user_id
 *
 * The followings are the available model relations:
 * @property Team $team
 * @property User $user
 * @property ProjectColumn[] $projectColumns
 * @property Sprint[] $sprints
 * @property Story[] $stories
 */
class Project extends CActiveRecord
{
	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Project the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'project';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		return array(
			array('name', 'required'),
			array('name', 'length', 'max'=>128),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		return array(
			'team' => array(self::BELONGS_TO, 'Team', 'team_id'),
			'user' => array(self::BELONGS_TO, 'User', 'user_id'),
			'projectColumns' => array(self::HAS_MANY, 'ProjectColumn', 'project_id'),
			'sprints' => array(self::HAS_MANY, 'Sprint', 'project_id'),
			'stories' => array(self::HAS_MANY, 'Story', 'project_id'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'name' => Yii::t('project', 'Name'),
			'active' => 'Active',
			'team_id' => 'Team',
			'user_id' => 'User',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models based on the search/filter conditions.
	 */
	public function search()
	{
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name);
		$criteria->compare('active', $this->active);
		$criteria->compare('team_id', $this->team_id);
		$criteria->compare('user_id', $this->user_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}

ScrumTool/protected/controllers/ProjectController.php
<?php

Yii::import('application.models.project.*');

class ProjectController extends Controller
{
	/**
	 * Filters
	 */
	public function filters()
	{
		return array(
			'accessControl',
			array('application.filters.HasProjectFilter + edit, archive, retrieve, delete'),
		);
	}
	
	/**
	 * Access rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',
				'actions' => array(
					'index',
					'create',
					'edit',
					'archive',
					'viewarchive',
					'retrieve',
					'delete'),
				'users' => array('@'),
			),
			// These actions are guarded manually. This is because projects of several
			// teams may appear on one page, and rights can be different for each team.
			// array('allow',
			// 	'actions' => array('create', 'edit', 'archive'),
			// 	'roles' => array('team_administrator'),
			// ),
			array('deny',
				'users' => array('?'),
			),
			array('deny',
				'users' => array('*'),
			),
		);
	}
	
	/**
	 * Default action - Show projects
	 */
	public function actionIndex()
	{
		// Testing
		/*
		$project = new Project;
		$project->id = 123;
		$projectForm = new ProjectForm;
		$projectForm->name = 'Test project';
		$projectForm->useColumn1 = true;
		$projectForm->column1Name = 'First';
		$projectForm->column1Relativity = 'before';
		$projectForm->column1OtherColumn = 'To do';
		$projectForm->useColumn2 = true;
		$projectForm->column2Name = 'Second';
		$projectForm->column2Relativity = 'after';
		$projectForm->column2OtherColumn = 'First';
		if(!$projectForm->validate())
		{
			echo $projectForm->errors;
		}
		$columns = $this->addProjectColumns($project, $projectForm);
		
		foreach($columns as $column)
		{
			echo $column->name . ' ' . $column->previous_column_id . '<br/>';
		}
		*/
		// End testing
		
		$this->render(
			'index',
			array(
				'teams' => $this->getTeams(),
				'ownProjects' => $this->getOwnProjects(true),
				)
			);
	}
	
	/**
	 * Create a project
	 */
	public function actionCreate()
	{
		$projectForm = new ProjectForm;
		
		$this->performAjaxValidation('project-form', $projectForm);
		
		if(isset($_POST['ProjectForm']))
		{
			$success = false;
			
			$projectForm->attributes = $_POST['ProjectForm'];
			$projectForm->purify();
			if($projectForm->validate())
			{
				$transaction = Yii::app()->db->beginTransaction();
				try
				{
					// Create the project
					$project = new Project;
					$project->name = $projectForm->name;
					$project->active = true;
					
					if($projectForm->isTeamSelected())
					{
						if(!$this->isTeamAdministratorById($projectForm->teamId))
						{
							throw new CHttpException(403);
						}
						
						$project->team_id = $projectForm->teamId;
					}
					else
					{
						$project->user_id = Yii::app()->user->getId();
					}
					
					if(!$project->save())
					{
						throw new CException('Error creating project.');
					}
					
					$this->addProjectColumns($project, $projectForm);
					
					$transaction->commit();
					
					$success = true;
				}
				catch(Exception $e)
				{
					$transaction->rollBack();
					
					$success = false;
				}
			}
			
			$this->formResponse(
				$success,
				'project-submit',
				$projectForm,
				$this->createUrl('project/index')
				);
		}
		
		$standardColumns = ProjectColumn::model()->findAllByPk(array(1, 2, 3, 4));
		$standardColumnNames = array();
		foreach($standardColumns as $standardColumn)
		{
			$standardColumnNames = array_merge(
				$standardColumnNames,
				array($standardColumn->name => Yii::t('columns', $standardColumn->name))
				);
		}
		
		$teams = array();
		foreach($this->getTeams() as $team)
		{
			if($this->isTeamAdministrator($team))
			{
				array_push($teams, $team);
			}
		}
		
		$this->displayForm(
			'project-render',
			'create',
			$projectForm,
			array(
				'teams' => $teams,
				'standardColumnNames' => $standardColumnNames,
				)
			);
	}
	
	/**
	 * Edit a project
	 */
	public function actionEdit($projectId)
	{
		$project = $this->getProject($projectId);
		
		$projectForm = new ProjectForm;
		$projectForm->name = $project->name;
		$projectForm->teamId = $project->team_id;
		
		$this->performAjaxValidation('project-form', $projectForm);
		
		if(isset($_POST['ProjectForm']))
		{
			$success = false;
			
			$projectForm->attributes = $_POST['ProjectForm'];
			$projectForm->purify();
			if($projectForm->validate())
			{
				$project->name = $projectForm->name;
				$project->team_id = $projectForm->teamId;
				
				$success = $project->save();
			}
			
			$this->formResponse(
				$success,
				'project-submit',
				$projectForm,
				$this->createUrl('project/index')
				);
		}
		
		$this->displayForm(
			'project-render',
			'edit',
			$projectForm,
			array(
				'teams' => array(),
				'standardColumnNames' => array(),
				)
			);
	}
	
	/**
	 * Archive a project
	 */
	public function actionArchive($projectId)
	{
		$db = Yii::app()->db;
		
		$rowsAffected = $db->createCommand()
			->update(
				'project',
				array('active' => false),
				'id = :projectId',
				array(':projectId' => $projectId)
				);
		
		$this->sendJsonResponse(
			$rowsAffected === 1,
			Yii::t('project', 'Can not archive project')
			);
	}
	
	/**
	 * View the archive
	 */
	public function actionViewarchive()
	{
		$this->renderPartial(
			'viewarchive',
			array(
				'teams' => $this->getTeams(),
				'ownProjects' => $this->getOwnProjects(false),
				)
			);
	}
	
	/**
	 * Retrieve a project from the archive - make it active again
	 */
	public function actionRetrieve($projectId)
	{
		$db = Yii::app()->db;
		
		$rowsAffected = $db->createCommand()
			->update(
				'project',
				array('active' => true),
				'id = :projectId',
				array(':projectId' => $projectId)
				);
		
		//$this->sendJsonResponse(
		//	$rowsAffected === 1,
		//	Yii::t('project', 'Can not retrieve project from the archive')
		//	);
		
		$this->redirect($this->createUrl('project/index'));
	}
	
	/**
	 * Delete a project
	 */
	public function actionDelete($projectId)
	{
		$db = Yii::app()->db;
		
		$rowsAffected = $db->createCommand()->delete(
			'project',
			'id = :projectId',
			array(':projectId' => $projectId)
			);
		
		$this->sendJsonResponse(
			$rowsAffected === 1,
			Yii::t('project', 'Can not delete the project')
			);
	}
	
	/**
	 * Creates the project-specific columns.
	 * Creates and arranges the columns in the correct order. Sets their previous_id.
	 * This function is part of the project creation process. It writes data to the
	 * database and must be called inside a transaction 'try' block.
	 * @param project Project the project, for which the columns are
	 * @param projectForm ProjectForm the form with the user input
	 */
	private function addProjectColumns($project, $projectForm)
	{
		if(!$projectForm->useColumn1 && !$projectForm->useColumn2)
		{
			return;
		}
		
		$projectSpecificColumns = array();
		
		if($projectForm->useColumn1)
		{
			$column = new ProjectColumn;
			$column->project_id = $project->id;
			$column->name = $projectForm->column1Name;
			
			array_push($projectSpecificColumns, $column);
		}
		
		if($projectForm->useColumn2)
		{
			$column = new ProjectColumn;
			$column->project_id = $project->id;
			$column->name = $projectForm->column2Name;
			
			array_push($projectSpecificColumns, $column);
		}
		
		if(count($projectSpecificColumns) > 1)
		{
			if($projectForm->column1OtherColumn === $projectForm->column2Name)
			{
				$projectSpecificColumns = array($projectSpecificColumns[1], $projectSpecificColumns[0]);
			}
		}
		
		$columns = ProjectColumn::model()->findAllByPk(array(1, 2, 3, 4));
		
		foreach($projectSpecificColumns as $projectColumn)
		{
			$relativity = '';
			$otherColumnName = '';
			if($projectColumn->name === $projectForm->column1Name)
			{
				$relativity = $projectForm->column1Relativity;
				$otherColumnName = $projectForm->column1OtherColumn;
			}
			else
			{
				$relativity = $projectForm->column2Relativity;
				$otherColumnName = $projectForm->column2OtherColumn;
			}
			
			foreach($columns as $index => $column)
			{
				if($relativity === 'before' &&
					$otherColumnName === $column->name
					)
				{
					array_splice($columns, $index, 0, array($projectColumn));
					break;
				}
				
				if($relativity === 'after' &&
					$otherColumnName === $column->name
					)
				{
					array_splice($columns, $index + 1, 0, array($projectColumn));
					break;
				}
			}
		}
		
		foreach($columns as $index => $column)
		{
			if($column->name === $projectForm->column1Name ||
				$column->name === $projectForm->column2Name
				)
			{
				if($index === 0)
				{
					$column->previous_column_id = 0;
				}
				else
				{
					$column->previous_column_id = $columns[$index - 1]->id;
				}
				
				if(!$column->save())
				{
					throw new CException('Can not create project-specific column.');
				}
			}
		}
	}
	
	/**
	 * Get the user's own projects
	 * @param active bool get the active or the inactive projects
	 * @return Project[..] array of the projects
	 */
	private function getOwnProjects($active)
	{
		$userId = Yii::app()->user->getId();
		
		$projects = Project::model()->findAllByAttributes(
			array(
				'user_id' => $userId,
				'active' => $active
				)
			);
		
		return $projects;
	}
	
	/**
	 * Find out if the user is the team administrator of the given team
	 * @param team Team the team
	 * @return bool Whether the user is the team administrator of the team
	 */
	protected function isTeamAdministrator($team)
	{
		return $this->isTeamAdministratorById($team->id);
	}
	
	/**
	 * Find out if the user is the team administrator of the team with the given team id
	 * @param teamId int the team's id
	 * @return bool Whether the user is the team administrator of the team
	 */
	private function isTeamAdministratorById($teamId)
	{
		$userId = Yii::app()->user->getId();
		$roleId = Yii::app()->params['roleIdentifiers']['team_administrator'];
		
		$criteria = new CDbCriteria;
		$criteria->alias = 'tmr';
		$criteria->join = 'JOIN team_member AS tm ON tmr.team_member_id = tm.id';

ScrumTool/protected/views/project/archivedprojectlist.php
<?php
	$isAdministrator = true;
	if($team !== null)
	{
		$isAdministrator = $this->isTeamAdministrator($team);
	}
?>

<ul>
	<?php foreach($projects as $project): ?>
		<?php if(!$project->active): ?>
			<li>
				<?php if($isAdministrator): ?>
					<div class="left">
						<span class="project-element"><?php echo $project->name; ?></span>
					</div>
					<div class="right">
						<div class="errorMessage"></div>
						<div class="project-actions">
							<a href="<?php echo $this->createUrl('project/retrieve', array('projectId' => $project->id)); ?>"><?php echo Yii::t('project', 'retrieve'); ?></a>
							<a href="<?php echo $this->createUrl('project/delete', array('projectId' => $project->id)); ?>" class="btnDeleteProject"><?php echo Yii::t('project', 'delete'); ?></a>
						</div>
					</div>
					<br style="clear: both;"/>
				<?php else: ?>
					<span class="project-element"><?php echo $project->name; ?></span>
				<?php endif; ?>
			</li>
		<?php endif; ?>
	<?php endforeach; ?>
</ul>

ScrumTool/protected/views/project/create.php
<?php
$this->pageTitle = Yii::app()->name . ' - ' . Yii::t('project', 'Create project');
?>

<div class="createProject">
	<?php echo $this->renderPartial('form', array('model' => $model, 'showSubmitButton' => $showSubmitButton, 'teams' => $teams, 'standardColumnNames' => $standardColumnNames)); ?>
</div><!-- createProject -->

ScrumTool/protected/views/project/edit.php
<?php
$this->pageTitle = Yii::app()->name . ' - ' . Yii::t('project', 'Edit project');
?>

<div class="editProject">
	<?php echo $this->renderPartial('form', array('model' => $model, 'showSubmitButton' => $showSubmitButton, 'teams' => $teams, 'standardColumnNames' => $standardColumnNames)); ?>
</div><!-- editProject -->

ScrumTool/protected/views/project/form.php
<div class="wide form">
	<?php $form = $this->beginWidget('CActiveForm', array(
		'id' => 'project-form',
		'enableAjaxValidation' => true,
		'enableClientValidation' => true,
		'clientOptions' => array(
			'validateOnSubmit' => true,
			'validateOnChange' => true,
			'validateOnType' => true,
			),
		)
	);
	?>
		<div class="row">
			<?php echo $form->label($model, 'name'); ?><br />
			<?php echo $form->textField($model, 'name'); ?>
			<?php echo $form->error($model,'name'); ?>
		</div>
		
		<div class="row inline">
			<?php
				$teamsData = array();
				foreach($teams as $team)
				{
					$teamsData += array($team->id => $team->name);
				}
				
				$teamsData = array(-1 => Yii::t('project', 'None')) + $teamsData;
				
				$showTeamSelect = !empty($teamsData);
			?>
			<?php if($showTeamSelect): ?>
				<?php echo $form->label($model, 'teamId'); ?><br />
				<?php echo $form->dropDownList($model, 'teamId', $teamsData); ?>
				<?php echo $form->error($model,'teamId'); ?>
			<?php endif; ?>
		</div>
		
		<?php
			$showAdditionalColumns = !empty($standardColumnNames);
		?>
		<?php if($showAdditionalColumns): ?>
			<span><?php echo Yii::t('project', 'Additional columns'); ?></span>
			<div class="row inline">
				<?php echo $form->label($model, 'useColumn1'); ?>
				<?php echo $form->checkBox($model, 'useColumn1'); ?>
				
				<?php echo $form->textField($model, 'column1Name', array('disabled' => 'disabled')); ?>
				
				<?php echo $form->dropDownList($model, 'column1Relativity', array('before' => Yii::t('project', 'before'), 'after' => Yii::t('project', 'after')), array('disabled' => 'disabled')); ?>
				<?php echo $form->dropDownList($model, 'column1OtherColumn', $standardColumnNames, array('disabled' => 'disabled')); ?>
			</div>
			
			<div class="row inline">
				<?php echo $form->label($model, 'useColumn2'); ?>
				<?php echo $form->checkBox($model, 'useColumn2'); ?>
				
				<?php echo $form->textField($model, 'column2Name', array('disabled' => 'disabled')); ?>
				
				<?php echo $form->dropDownList($model, 'column2Relativity', array('before' => Yii::t('project', 'before'), 'after' => Yii::t('project', 'after')), array('disabled' => 'disabled')); ?>
				<?php echo $form->dropDownList($model, 'column2OtherColumn', $standardColumnNames, array('disabled' => 'disabled')); ?>
			</div>
		<?php endif; ?>
		
		<?php if($showSubmitButton): ?>
			<div class="buttons">
				<?php echo CHTML::submitButton(Yii::t('project', 'Submit')); ?>
			</div>
		<?php endif; ?>
		
	<?php $this->endWidget(); ?>
</div><!-- form -->

<script type="text/javascript">
/*<![CDATA[*/
	jQuery(document).ready(function()
	{
		jQuery('#ProjectForm_column1Name, #ProjectForm_column2Name').each(function()
		{
			var element = jQuery(this);
			var value = element.attr('value');
			element.data('value', value);
		});
		
		function enableColumnElements(columnIndex, enable)
		{
			jQuery('#ProjectForm_column' + columnIndex + 'Name').attr('disabled', !enable);
			jQuery('#ProjectForm_column' + columnIndex + 'Relativity').attr('disabled', !enable);
			jQuery('#ProjectForm_column' + columnIndex + 'OtherColumn').attr('disabled', !enable);
			
			var columnName = jQuery('#ProjectForm_column' + columnIndex + 'Name').attr('value');
			
			if(columnName.length > 0)
			{
				var otherColumnSelectId = '';
				if(columnIndex === 1)
				{
					otherColumnSelectId = 'ProjectForm_column2OtherColumn';
				}
				else if(columnIndex === 2)
				{
					otherColumnSelectId = 'ProjectForm_column1OtherColumn';
				}
				
				if(enable)
				{
					var option = jQuery('<option>')
						.attr('value', columnName)
						.text(columnName);
					
					jQuery('#' + otherColumnSelectId).append(option);
				}
				else
				{
					var option = jQuery('#' + otherColumnSelectId + ' option[value=' + columnName + ']');
					if(option !== null)
					{
						option.remove();
					}
				}
			}
		}
		
		jQuery('#ProjectForm_useColumn1').live('change', function()
		{
			var checkbox = jQuery(this);
			if(checkbox.attr('checked') === 'checked')
			{
				enableColumnElements(1, true);
			}
			else
			{
				enableColumnElements(1, false);
			}
		});
		
		jQuery('#ProjectForm_useColumn2').live('change', function()
		{
			var checkbox = jQuery(this);
			if(checkbox.attr('checked') === 'checked')
			{
				enableColumnElements(2, true);
			}
			else
			{
				enableColumnElements(2, false);
			}
		});
		
		jQuery('#ProjectForm_column1Name').live('change', function()
		{
			var element = jQuery(this);
			var previousValue = element.data('value');
			var value = element.attr('value');
			var option = jQuery('<option>')
				.attr('value', value)
				.text(value);
			
			jQuery('#ProjectForm_column2OtherColumn option[value=' + previousValue + ']').remove();
			
			if(value.length !== 0)
			{
				jQuery('#ProjectForm_column2OtherColumn').append(option);
			}
			
			element.data('value', value);
		});
		
		jQuery('#ProjectForm_column2Name').live('change', function()
		{
			var element = jQuery(this);
			var previousValue = element.data('value');
			var value = element.attr('value');
			var option = jQuery('<option>')
				.attr('value', value)
				.text(value);
			
			jQuery('#ProjectForm_column1OtherColumn option[value=' + previousValue + ']').remove();
			
			if(value.length !== 0)
			{
				jQuery('#ProjectForm_column1OtherColumn').append(option);
			}
			
			element.data('value', value);
		});
	});
/*]]>*/
</script>

ScrumTool/protected/views/project/index.php
<?php
$this->pageTitle = Yii::app()->name . ' - '. Yii::t('project', 'Projects');
?>

<div class="centered-div project">

	<!-- Teams' projects -->
	<?php foreach($teams as $team): ?>
		<?php
			$isAdministrator = $this->isTeamAdministrator($team);
		?>
		<div class="project-title">
			<span><?php echo $team->name; ?></span>
		</div>

		<div class="list">
			<?php if($this->hasActiveProjects($team->id)): ?>
				<?php $this->renderPartial('projectList', array('team' => $team, 'projects' => $team->projects)); ?>
			<?php else: ?>
				<?php if($isAdministrator): ?>
					<div class="description">
						<span><?php echo Yii::t('project', 'This team does not have any projects yet. You can start one by clicking on the "Create project" button.'); ?></span>
					</div>
				<?php else: ?>
					<div class="description">
						<span><?php echo Yii::t('project', 'This team does not have any projects yet. Contact your Team administrator so he/she can start one.'); ?></span>
					</div>
				<?php endif; ?>
			<?php endif; ?>
		</div><!-- list -->
	<?php endforeach; ?>
	
	<!-- Own projects -->
	<div class="project-title">
		<span><?php echo Yii::t('project', 'Own projects'); ?></span>
	</div>
	
	<div class="list">
		<?php if(!empty($ownProjects)): ?>
			<?php $this->renderPartial('projectList', array('team' => null, 'projects' => $ownProjects)); ?>
		<?php else: ?>
			<div class="description">
				<span><?php echo Yii::t('project', 'You do not have any projects yet. You can start one by clicking on the "Create project" button.'); ?></span>
			</div>
		<?php endif; ?>
	</div><!-- list -->

	<a id="btnCreateProject" href="<?php echo $this->createUrl('project/create'); ?>" class="button"><?php echo Yii::t('project', 'Create project'); ?></a>
	<a id="btnViewArchive" href="<?php echo $this->createUrl('project/viewarchive'); ?>" class="button"><?php echo Yii::t('project', 'View archive'); ?></a>
	
	<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/assets/javascript/jquery-ui/jquery-ui.min.js"></script>
	<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/assets/javascript/formDialog.js"></script>
	<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/assets/javascript/confirmationDialog.js"></script>
	<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/assets/javascript/infoDialog.js"></script>
		
	<script type="text/javascript">
	/*<![CDATA[*/
		jQuery(document).ready(function()
		{
			function updateProjects(data)
			{
				window.location.replace('<?php echo $this->createUrl('project/index'); ?>');
			}
			
			jQuery('#btnCreateProject').live('click', function()
			{
				var settings =
				{
					'contentUrl': jQuery(this).attr('href'),
					'actionRender': 'project-render',
					'actionSubmit': 'project-submit',
					'submitSuccessCallback': updateProjects,
					'title': '<?php echo Yii::t('project', 'Create project'); ?>'
				};
				
				return createFormDialog(settings);
			});
			
			jQuery('.btnEditProject').live('click', function()
			{
				var settings =
				{
					'contentUrl': jQuery(this).attr('href'),
					'actionRender': 'project-render',
					'actionSubmit': 'project-submit',
					'submitSuccessCallback': updateProjects,
					'title': '<?php echo Yii::t('project', 'Edit project'); ?>'
				};
				
				return createFormDialog(settings);
			});
			
			jQuery('.btnArchiveProject').live('click', function()
			{
				var settings =
				{
					'url': jQuery(this).attr('href'),
					'title': '<?php echo Yii::t('general', 'Confirmation required'); ?>',
					'content': '<?php echo Yii::t('project', 'Are you sure you want to archive this project?'); ?>',
					'successCallback': updateProjects,
				};
				
				return confirmationDialog(settings);
			});
			
			jQuery('#btnViewArchive').live('click', function()
			{
				var settings =
				{
					'contentUrl': jQuery(this).attr('href'),
					'title': '<?php echo Yii::t('project', 'Projects archive'); ?>',
				};
				
				return createInfoDialog(settings);
			});
		});
	/*]]>*/
	</script>
	
</div><!-- project -->

ScrumTool/protected/views/project/projectList.php
<?php
	$isAdministrator = true;
	if($team !== null)
	{
		$isAdministrator = $this->isTeamAdministrator($team);
	}
?>

<ul>
	<?php foreach($projects as $project): ?>
		<?php if($project->active): ?>
			<li>
				<?php $element = '<a href="' . $this->createUrl('backlog/index', array('projectId' => $project->id)) . '" class="project-element">' . $project->name . '</a>'; ?>
				
				<?php if($isAdministrator): ?>
					<div class="left">
						<?php echo $element; ?>
					</div>
					<div class="right">
						<div class="errorMessage"></div>
						<div class="project-actions">
							<a href="<?php echo $this->createUrl('project/edit', array('projectId' => $project->id)); ?>" class="btnEditProject"><?php echo Yii::t('project', 'edit'); ?></a>
							<a href="<?php echo $this->createUrl('project/archive', array('projectId' => $project->id)); ?>" class="btnArchiveProject"><?php echo Yii::t('project', 'archive'); ?></a>
						</div>
					</div>
					<br style="clear: both;"/>
				<?php else: ?>
					<?php echo $element; ?>
				<?php endif; ?>
			</li>
		<?php endif; ?>
	<?php endforeach; ?>
</ul>

ScrumTool/protected/views/project/viewarchive.php
<?php
$this->pageTitle = Yii::app()->name . ' - '. Yii::t('project', 'Projects archive');
?>

<div class="centered-div project">

	<?php $atLeastOneProjectArchived = false; ?>
	
	<!-- Teams' projects -->
	<?php foreach($teams as $team): ?>
		<?php if($this->hasInactiveProjects($team->id)): ?>
			<?php $atLeastOneProjectArchived = true; ?>
			
			<?php
				$isAdministrator = $this->isTeamAdministrator($team);
			?>
			<div class="project-title">
				<span><?php echo $team->name; ?></span>
			</div>

			<div class="list">
				<?php $this->renderPartial('archivedprojectlist', array('team' => $team, 'projects' => $team->projects)); ?>
			</div><!-- list -->
		<?php endif; ?>
	<?php endforeach; ?>
	
	<!-- Own projects -->
	<?php if(!empty($ownProjects)): ?>
		<?php $atLeastOneProjectArchived = true; ?>
		
		<div class="project-title">
			<span><?php echo Yii::t('project', 'Own projects'); ?></span>
		</div>
		
		<div class="list">
				<?php $this->renderPartial('archivedprojectlist', array('team' => null, 'projects' => $ownProjects)); ?>
		</div><!-- list -->
	<?php endif; ?>
	
	<?php if(!$atLeastOneProjectArchived): ?>
		<div class="description">
			<?php echo Yii::t('project', 'There are no archived projects.'); ?>
		</div>
	<?php endif; ?>
	
	<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/assets/javascript/jquery-ui/jquery-ui.min.js"></script>
	<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/assets/javascript/confirmationDialog.js"></script>
		
	<script type="text/javascript">
	/*<![CDATA[*/
		jQuery(document).ready(function()
		{
			function redirectToProjects(data)
			{
				window.location.replace('<?php echo $this->createUrl('project/index'); ?>');
			}
			
			jQuery('.btnDeleteProject').click(function()
			{
				var settings =
				{
					'url': jQuery(this).attr('href'),
					'title': '<?php echo Yii::t('general', 'Confirmation required'); ?>',
					'content': '<?php echo Yii::t('project', 'Are you sure you want to delete this project? Note that this action is irreversible!'); ?>',
					'successCallback': redirectToProjects,
				};
				
				return confirmationDialog(settings);
			});
		});
	/*]]>*/
	</script>
	
</div><!-- project -->