ScrumTool/protected/controllers/BoardController.php
<?php

Yii::import('application.classes.ColumnArranger');
Yii::import('application.classes.TaskStoryPointsCalculator');

class BoardController extends Controller
{
	/**
	 * Filters
	 */
	public function filters()
	{
		return array(
			'accessControl',
			array('application.filters.HasSprintFilter'),
		);
	}
	
	/**
	 * Access rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',
				'actions' => array('index' ,'move', 'columnTaskList', 'rearrangeColumnTask', 'assign', 'unassign'),
				'roles' => array('user'),
			),
			array('deny',
				'users' => array('?'),
			),
			array('deny',
				'users' => array('*'),
			),
		);
	}
	
	/**
	 * Default action
	 * @param projectId int project, which the sprint belongs to
	 * @param sprintId int id of the sprint whose SCRUM board to display
	 */
	public function actionIndex($projectId, $sprintId)
	{
		$sprint = $this->getSprintSafe($sprintId, $projectId);
		
		$columnArranger = new ColumnArranger;
		$columns = $columnArranger->getArrangedColumns($projectId);
		
		$sprintColumnTasks = array();
		foreach($columns as $column)
		{
			$columnTasks = SprintColumnTask::model()->findAllByAttributes(
				array('sprint_id' => $sprintId, 'column_id' => $column->id)
				);
			if($columnTasks !== null)
			{
				$columnTasks = $this->arrangeColumnTasks($columnTasks);
				$sprintColumnTasks = $sprintColumnTasks + array($column->id => $columnTasks);
			}
		}
		
		$taskStoryPoints = TaskStoryPointsCalculator::calculate($sprintId, $columns);
		
		$taskAssignees = $this->getTaskAssignees($sprintId);
		
		$currentUser = User::model()->findByPk(Yii::app()->user->getId());
		$currentUserName = $currentUser->username;
		if($currentUser->name !== null && !empty($currentUser->name))
		{
			$currentUserName = $currentUser->name;
		}
		
		$this->render('index', array(
			'projectId' => $projectId,
			'sprint' => $sprint,
			'columns' => $columns,
			'sprintColumnTasks' => $sprintColumnTasks,
			'taskStoryPoints' => $taskStoryPoints,
			'taskAssignees' => $taskAssignees,
			'currentUserName' => $currentUserName,
			)
		);
	}
	
	/**
	 * Move a task from one column to another
	 * @param $projectId int id of the project
	 * @param sprintId int id of the sprint
	 */
	public function actionMove($projectId, $sprintId)
	{
		$taskId = $this->getPostDataSafe('taskId');
		$fromColumnId = $this->getPostDataSafe('fromColumnId');
		$toColumnId = $this->getPostDataSafe('toColumnId');
		$previousId = $this->getPostDataSafe('previousId');
		
		// Test
		//$taskId = $_GET['taskId'];
		//$toColumnId = $_GET['toColumnId'];
		//$previousId = $_GET['previousId'];
		
		$task = $this->getTaskAndValidateInputData($projectId, $sprintId, $taskId, $fromColumnId, $toColumnId);
		
		$success = false;
		
		$transaction = Yii::app()->db->beginTransaction();
		try
		{
			// Find the entry
			$sprintColumnTask = $task->sprintColumnTasks[0];
			
			$fromColumnId = $sprintColumnTask->column_id;
			
			// Change ordering in the previous column
			$previousColumnNextTask = SprintColumnTask::model()->findByAttributes(
				array(
					'previous_id' => $sprintColumnTask->task->id,
					'sprint_id' => $sprintId,
					'column_id' => $fromColumnId
					)
				);
			if($previousColumnNextTask !== null)
			{
				//echo $sprintColumnTask->previous_id;
				$previousColumnNextTask->previous_id = $sprintColumnTask->previous_id;
				$previousColumnNextTask->save();
			}
			
			// Change ordering in the new column
			$newColumnNextTask = SprintColumnTask::model()->findByAttributes(
				array(
					'previous_id' => $previousId,
					'sprint_id' => $sprintId,
					'column_id' => $toColumnId
					)
				);
			if($newColumnNextTask !== null)
			{
				$newColumnNextTask->previous_id = $sprintColumnTask->task->id;
				$newColumnNextTask->save();
			}
			
			// Update
			$sprintColumnTask->column_id = $toColumnId;
			$sprintColumnTask->previous_id = $previousId;
			if(!$sprintColumnTask->save())
			{
				throw new CException('Can not move task to another column.');
			}
			
			// Log the moving
			$sprintTaskMove = new SprintTaskMove;
			$sprintTaskMove->sprint_id = $sprintId;
			$sprintTaskMove->task_id = $taskId;
			$sprintTaskMove->from_column_id = $fromColumnId;
			$sprintTaskMove->to_column_id = $toColumnId;
			if(!$sprintTaskMove->save())
			{
				throw new CException('Can not log the task moving to another column.');
			}
			
			$transaction->commit();
			
			$success = true;
		}
		catch(Exception $e)
		{
			$transaction->rollBack();
			
			$success = false;
		}
		
		$this->sendJsonResponse($success, 'There was an error moving the task.');
	}
	
	/**
	 * Move a task from inside its own column - change its position
	 * @param $projectId int id of the project
	 * @param sprintId int id of the sprint
	 */
	public function actionRearrangeColumnTask($projectId, $sprintId)
	{
		$taskId = $this->getPostDataSafe('taskId');
		$previousId = $this->getPostDataSafe('previousId');
		
		$task = $this->getTaskAndValidateInputData($projectId, $sprintId, $taskId);
		
		$success = false;
		
		$transaction = Yii::app()->db->beginTransaction();
		try
		{
			// Find the entry
			$sprintColumnTask = $task->sprintColumnTasks[0];
			
			$columnId = $sprintColumnTask->column_id;
			
			// Change ordering at the previous place of the task
			$previousNextTask = SprintColumnTask::model()->findByAttributes(
				array(
					'previous_id' => $sprintColumnTask->task->id,
					'sprint_id' => $sprintId,
					'column_id' => $columnId
					)
				);
			if($previousNextTask !== null)
			{
				$previousNextTask->previous_id = $sprintColumnTask->previous_id;
				$previousNextTask->save();
			}
			
			// Change ordering at the new place of the task
			$newNextTask = SprintColumnTask::model()->findByAttributes(
				array(
					'previous_id' => $previousId,
					'sprint_id' => $sprintId,
					'column_id' => $columnId
					)
				);
			if($newNextTask !== null)
			{
				$newNextTask->previous_id = $sprintColumnTask->task->id;
				$newNextTask->save();
			}
			
			// Update
			$sprintColumnTask->previous_id = $previousId;
			if(!$sprintColumnTask->save())
			{
				throw new CException('Can not move task to another column.');
			}
			
			$transaction->commit();
			
			$success = true;
		}
		catch(Exception $e)
		{
			$transaction->rollBack();
			
			$success = false;
		}
		
		$this->sendJsonResponse($success, 'There was an error rearranging the task.');
	}
	
	/**
	 * Assign the current user to a task
	 * @param $projectId int id of the project
	 * @param sprintId int id of the sprint
	 */
	public function actionAssign($projectId, $sprintId)
	{
		$taskId = $this->getPostDataSafe('taskId');
		
		$success = false;
		
		$sprintTask = SprintTask::model()->findByAttributes(
			array(
				'sprint_id' => $sprintId,
				'task_id' => $taskId,
				)
			);
		if($sprintTask === null)
		{
			throw new CHttpException(403);
		}
		
		$sprintTaskAssignment = new SprintTaskAssignment;
		$sprintTaskAssignment->sprint_task_id = $sprintTask->id;
		$sprintTaskAssignment->user_id = Yii::app()->user->getId();
		$success = $sprintTaskAssignment->save();
		
		$this->sendJsonResponse($success, 'There was an error assigning yourself to the task.');
	}
	
	/**
	 * Unassign the current user to a task
	 * @param $projectId int id of the project
	 * @param sprintId int id of the sprint
	 */
	public function actionUnassign($projectId, $sprintId)
	{
		$taskId = $this->getPostDataSafe('taskId');
		
		$success = false;
		
		$criteria = new CDbCriteria;
		$criteria->alias = 'sta';
		$criteria->join = 'LEFT JOIN sprint_task as st ON sta.sprint_task_id = st.id';
		$criteria->condition = 'st.sprint_id = :sprintId AND st.task_id = :taskId AND sta.user_id = :userId';
		$criteria->params = array(
			':sprintId' => $sprintId,
			':taskId' => $taskId,
			':userId' => Yii::app()->user->getId()
			);
		
		$sprintTaskAssignment = SprintTaskAssignment::model()->find($criteria);
		if($sprintTaskAssignment === null)
		{
			throw new CHttpException(403);
		}
		
		$success = $sprintTaskAssignment->delete();
		
		$this->sendJsonResponse($success, 'There was an error unassigning yourself from the task.');
	}
	
	/**
	 * Render the list of tasks for a column
	 * @param sprintId int id of the sprint
	 */
	public function actionColumnTaskList($projectId, $sprintId, $columnId)
	{
		$project = $this->getProject($projectId, true);
		$sprint = $this->getSprintSafe($sprintId, $projectId);
		$column = $this->getColumnSafe($columnId, $project);
		
		$columnArranger = new ColumnArranger;
		$columns = $columnArranger->getArrangedColumns($projectId);
		
		$columnTasks = SprintColumnTask::model()->findAllByAttributes(
			array('sprint_id' => $sprintId, 'column_id' => $column->id)
			);
		
		$taskStoryPoints = TaskStoryPointsCalculator::calculate($sprintId, $columns);
		
		$taskAssignees = $this->getTaskAssignees($sprintId);
		
		$currentUser = User::model()->findByPk(Yii::app()->user->getId());
		$currentUserName = $currentUser->username;
		if($currentUser->name !== null && !empty($currentUser->name))
		{
			$currentUserName = $currentUser->name;
		}
		
		$this->renderPartial(
			'columnTaskList',
			array(
				'projectId' => $projectId,
				'sprint' => $sprint,
				'columnTasks' => $columnTasks,
				'taskStoryPoints' => $taskStoryPoints,
				'taskAssignees' => $taskAssignees,
				'currentUserName' => $currentUserName,
				)
			);
	}
	
	/**
	 * Get task and verify the input data for moving a task.
	 * Verifies the task's validity.
	 * Redirects the user to the main page if the input data is not verified.
	 * @param sprintId int id of the sprint
	 * @param taskId int id of the task
	 * @param toColumnId int id of the column that the task is moved to,
	 * null if the task is moved to the same column
	 * @return Task the task
	 */
	private function getTaskAndValidateInputData($projectId, $sprintId, $taskId, $fromColumnId = null, $toColumnId = null)
	{
		if($toColumnId !== null)
		{
			if((int)$toColumnId !== 1
				&& (int)$toColumnId !== 2

ScrumTool/protected/controllers/IndexController.php
<?php

Yii::import('application.models.index.*');

class IndexController extends Controller
{
	/**
	 * Filters
	 */
	public function filters()
	{
		return array(
			'accessControl',
		);
	}
	
	/**
	 * Access rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',
				'actions' => array('selectLanguage'),
				'users' => array('*'),
			),
			array('allow',
				'actions' => array('login'),
				'users' => array('?'),
			),
			array('deny',
				'actions' => array('login'),
				'users' => array('@'),
			),
			/*
			// TEST
			array('deny',
				'actions' => array('logout'),
				'roles' => array('scrum_master'),
			),
			*/
			array('allow',
				'actions' => array('logout'),
				'users' => array('@'),
			),
			array('deny',
				'actions' => array('logout'),
				'users' => array('?'),
			),
			array('deny',
				'actions' => array('logout'),
				'users' => array('*'),
			),
		);
	}
	
	/**
	 * Default action - Home page
	 */
	public function actionIndex()
	{
		if(Yii::app()->user->isGuest)
		{
			$this->render('index');
		}
		else
		{
			$user = User::model()->findByPk(Yii::app()->user->getId());
			$name = $user->username;
			if($user->name !== null && !empty($user->name))
			{
				$name = $user->name;
			}
			
			$teams = $this->getTeams();
			
			$hasTeams = !empty($teams);
			$hasProjects = false;
			
			$ownProjects = Project::model()->findAllByAttributes(
				array('user_id' => $user->id)
				);
			if(empty($ownProjects))
			{
				foreach($teams as $team)
				{
					if(!empty($team->projects))
					{
						$hasProjects = true;
						break;
					}
				}
			}
			else
			{
				$hasProjects = true;
			}
			
			$this->render(
				'memberindex',
				array(
					'name' => $name,
					'hasTeams' => $hasTeams,
					'hasProjects' => $hasProjects,
					)
				);
		}
	}
	
	/**
	 * Select language
	 * @param language string the selected language
	 */
	public function actionSelectLanguage($language)
	{
		Yii::app()->language = $language;
		Yii::app()->request->cookies['language'] = new CHttpCookie('language', $language);
		$this->redirect($this->getPreviousPage());
	}
	
	/**
	 * Logs in an user
	 * Show the form where the user enters their username and password
	 * Validates and logs the user in
	 */
	public function actionLogin()
	{
		$loginForm = new LoginForm;
		
		$this->performAjaxValidation('login-form', $loginForm);
		
		// Collect user input data
		if(isset($_POST['LoginForm']))
		{
			$loginForm->attributes = $_POST['LoginForm'];
			$loginForm->purify();
			if($loginForm->validate() && $loginForm->login())
			{
				$this->redirect(Yii::app()->user->returnUrl);
			}
		}
		
		// Display login form
		$this->render('login', array(
			'model' => $loginForm)
			);
	}
	
	/**
	 * Registers a new user
	 * Shows a form where the user enters their data
	 * Validates and creates a new user
	 */
	public function actionRegister()
	{
		$registerForm = new RegisterForm;
		
		$this->performAjaxValidation('register-form', $registerForm);
		
		// Collect user input data
		if(isset($_POST['RegisterForm']))
		{
			$registerForm->attributes = $_POST['RegisterForm'];
			$registerForm->purify();
			if($registerForm->validate())
			{
				$user = new User;
				$user->username = $registerForm->username;
				
				$salt = $this->createSalt();
				$user->password = $user->getPasswordHash($registerForm->password, $salt);
				$user->salt = $salt;
				
				$user->email = $registerForm->email;
				if($registerForm->name !== null && strlen($registerForm->name) > 0)
				{
					$user->name = $registerForm->name;
				}
				
				if($user->validate())
				{
					$user->save();
					$this->redirect(Yii::app()->user->returnUrl);
				}
			}
		}
		
		// Display register form
		$this->render('register', array(
			'model' => $registerForm)
			);
	}
	
	/**
	 * Logs out the current user and redirect to homepage.
	 */
	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect(Yii::app()->homeUrl);
	}
	
	/**
	 * Renders the error page
	 */
	public function actionError()
	{
		if($error = Yii::app()->errorHandler->error)
	    {
	    	if(Yii::app()->request->isAjaxRequest)
			{
	    		echo $error['message'];
			}
	    	else
			{
	        	$this->render('error', $error);
			}
	    }
	}
	
	private function createSalt()
	{
		$saltLength = Yii::app()->params['saltLength'];
		
		$salt = substr(hash('sha256', uniqid(rand(), true)), 0, $saltLength);
		
		return $salt;
	}
}

ScrumTool/protected/views/layouts/column1.php
<?php $this->beginContent('//layouts/main'); ?>
<div class="container">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<?php $this->endContent(); ?>

ScrumTool/protected/views/layouts/column2.php
<?php $this->beginContent('//layouts/main'); ?>
<div class="two-column-wrap">
	<div class="two-column-left">
		<?php echo $content; ?>
	</div>
	<div class="two-column-right">
		<?php if($this->hasCurrentProject()): ?>
			<?php $project = $this->getCurrentProject(); ?>
			<div class="rightmenu">
				<div class="rightmenu-title">
					<span><?php echo $project->name; ?></span>
				</div>
				<ul>
					<li><a href="<?php echo $this->createUrl('backlog/index', array('projectId' => $project->id)); ?>"><?php echo Yii::t('rightmenu', 'Backlog'); ?></a></li>
					<li><a href="<?php echo $this->createUrl('sprintPlan/index', array('projectId' => $project->id)); ?>"><?php echo Yii::t('rightmenu', 'Sprint planning'); ?></a></li>
					<li><a href="<?php echo $this->createUrl('history/index', array('projectId' => $project->id)); ?>"><?php echo Yii::t('rightmenu', 'Sprint history'); ?></a></li>
				</ul>
			</div><!-- rightmenu -->
			
			<?php
				$sprint = null;
				if($this->hasCurrentSprint())
				{
					$sprint = $this->getSprintSafe($this->getCurrentSprintId(), $project->id);
				}
				else
				{
					$sprint = $this->getLatestSprint($project->id);
				}
			?>
			<?php if($sprint !== null): ?>
				<div class="rightmenu">
					<div class="rightmenu-title">
						<span><?php echo $sprint->name; ?></span>
					</div>
					<ul>
						<li><a href="<?php echo $this->createUrl('dashboard/index', array('projectId' => $project->id, 'sprintId' => $sprint->id)); ?>"><?php echo Yii::t('rightmenu', 'Dashboard'); ?></a></li>
						<li><a href="<?php echo $this->createUrl('board/index', array('projectId' => $project->id, 'sprintId' => $sprint->id)); ?>"><?php echo Yii::t('rightmenu', 'Board'); ?></a></li>
					</ul>
				</div><!-- rightmenu -->
			<?php endif; ?>
		<?php else: ?>
			<div class="rightmenu">
				<div class="rightmenu-title">
					<span><?php echo Yii::t('rightmenu', 'No project selected'); ?></span>
				</div>
			</div>
		<?php endif; ?>
	</div><!-- right -->
</div><!-- two-column-wrap -->
<?php $this->endContent(); ?>

ScrumTool/protected/views/layouts/main.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo Yii::app()->language; ?>" lang="<?php echo Yii::app()->language; ?>">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="content-language" content="en<?php if(Yii::app()->language !== 'en') echo ', ' . Yii::app()->language; ?>" />

	<!-- blueprint CSS framework -->
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css" media="screen, projection" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print" />
	<!--[if lt IE 8]>
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection" />
	<![endif]-->

	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css" />
	
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/jquery-ui-themes/ui-default/jquery.ui.all.css" />
	
	<?php
		$baseUrl = Yii::app()->baseUrl;
		$clientScript = Yii::app()->getClientScript();
		$clientScript->registerScriptFile($baseUrl . '/assets/javascript/jquery.min.js');
	?>

	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

<body>
	<?php
		$user = !Yii::app()->user->isGuest ? User::model()->findByPk(Yii::app()->user->getId()) : null;
		$userPrettyName = '';
		if($user !== null)
		{
			if($user->name !== null && strlen($user->name) > 0)
			{
				$userPrettyName = $user->name;
			}
			else
			{
				$userPrettyName = $user->username;
			}
		}
	?>

	<div class="page">
		
		<div class="header">
			<div class="logo"><?php echo CHtml::encode(Yii::app()->name); ?></div>
			<ul class="mainmenu">
				<li><a href="<?php echo $this->createUrl('/index'); ?>"><?php echo Yii::t('mainmenu', 'Home'); ?></a></li>
				<?php if(Yii::app()->user->isGuest): ?>
					<li><a href="<?php echo $this->createUrl('index/login'); ?>"><?php echo Yii::t('mainmenu', 'Sign in'); ?></a></li>
				<?php else: ?>
					<?php if(!Yii::app()->user->isGuest): ?>
						<li>
							<a class="dropdown" href="#"><?php echo $userPrettyName; ?> <span>&#x25BE;</span></a>
							<ul class="dropdown">
								<li><span class="bigger"><?php echo $userPrettyName; ?></span></li>
								<li><?php echo Yii::t('mainmenu', 'Username: {username}', array('{username}' => Yii::app()->user->name)); ?></li>
								<li class="separator"></li>
								<li><a href="<?php echo $this->createUrl('/team'); ?>"><?php echo Yii::t('mainmenu', 'Teams'); ?></a></li>
								<li><a href="<?php echo $this->createUrl('/project'); ?>"><?php echo Yii::t('mainmenu', 'Projects'); ?></a></li>
								<li class="separator"></li>
								<li><a href="<?php echo $this->createUrl('index/logout'); ?>"><?php echo Yii::t('mainmenu', 'Sign out'); ?></a></li>
							</ul>
						</li>
					<?php endif; ?>
				<?php endif; ?>
				
				<li>
					<a class="dropdown" href="#"><?php echo Yii::t('mainmenu', 'Options'); ?> <span>&#x25BE;</span></a>
					<ul class="dropdown options">
						<li>
							<?php echo Yii::t('mainmenu', 'Language:'); ?>
							<ul class="language">
								<li class="first"><a href="<?php echo $this->createUrl('index/selectLanguage', array('language' => 'bg')) ?>">bg</a></li>
								<li><a href="<?php echo $this->createUrl('index/selectLanguage', array('language' => 'en_us')) ?>">en</a></li>
							</ul>
						</li>
					</ul>
				</li>
			</ul><!-- mainmenu -->
			<br class="clearboth"/>
		</div><!-- header -->
		
		<div class="content">
			<?php echo $content; ?>
		</div><!-- content -->

		<div class="push">
		</div>
	</div><!-- page -->

	<div class="footer">
		<?php echo Yii::t('general', 'Copyright &copy; {date} by Lyubomir Vasilev.<br />All Rights Reserved.<br />', array('{date}' => date('Y'))); ?>
	</div><!-- footer -->

</body>
</html>