ScrumTool/protected/controllers/BoardController.php
<?php

Yii::import('application.classes.ColumnArranger');
Yii::import('application.classes.TaskStoryPointsCalculator');

class BoardController extends Controller
{
	/**
	 * Filters
	 */
	public function filters()
	{
		return array(
			'accessControl',
			array('application.filters.HasSprintFilter'),
		);
	}
	
	/**
	 * Access rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',
				'actions' => array('index' ,'move', 'columnTaskList', 'rearrangeColumnTask', 'assign', 'unassign'),
				'roles' => array('user'),
			),
			array('deny',
				'users' => array('?'),
			),
			array('deny',
				'users' => array('*'),
			),
		);
	}
	
	/**
	 * Default action
	 * @param projectId int project, which the sprint belongs to
	 * @param sprintId int id of the sprint whose SCRUM board to display
	 */
	public function actionIndex($projectId, $sprintId)
	{
		$sprint = $this->getSprintSafe($sprintId, $projectId);
		
		$columnArranger = new ColumnArranger;
		$columns = $columnArranger->getArrangedColumns($projectId);
		
		$sprintColumnTasks = array();
		foreach($columns as $column)
		{
			$columnTasks = SprintColumnTask::model()->findAllByAttributes(
				array('sprint_id' => $sprintId, 'column_id' => $column->id)
				);
			if($columnTasks !== null)
			{
				$columnTasks = $this->arrangeColumnTasks($columnTasks);
				$sprintColumnTasks = $sprintColumnTasks + array($column->id => $columnTasks);
			}
		}
		
		$taskStoryPoints = TaskStoryPointsCalculator::calculate($sprintId, $columns);
		
		$taskAssignees = $this->getTaskAssignees($sprintId);
		
		$currentUser = User::model()->findByPk(Yii::app()->user->getId());
		$currentUserName = $currentUser->username;
		if($currentUser->name !== null && !empty($currentUser->name))
		{
			$currentUserName = $currentUser->name;
		}
		
		$this->render('index', array(
			'projectId' => $projectId,
			'sprint' => $sprint,
			'columns' => $columns,
			'sprintColumnTasks' => $sprintColumnTasks,
			'taskStoryPoints' => $taskStoryPoints,
			'taskAssignees' => $taskAssignees,
			'currentUserName' => $currentUserName,
			)
		);
	}
	
	/**
	 * Move a task from one column to another
	 * @param $projectId int id of the project
	 * @param sprintId int id of the sprint
	 */
	public function actionMove($projectId, $sprintId)
	{
		$taskId = $this->getPostDataSafe('taskId');
		$fromColumnId = $this->getPostDataSafe('fromColumnId');
		$toColumnId = $this->getPostDataSafe('toColumnId');
		$previousId = $this->getPostDataSafe('previousId');
		
		// Test
		//$taskId = $_GET['taskId'];
		//$toColumnId = $_GET['toColumnId'];
		//$previousId = $_GET['previousId'];
		
		$task = $this->getTaskAndValidateInputData($projectId, $sprintId, $taskId, $fromColumnId, $toColumnId);
		
		$success = false;
		
		$transaction = Yii::app()->db->beginTransaction();
		try
		{
			// Find the entry
			$sprintColumnTask = $task->sprintColumnTasks[0];
			
			$fromColumnId = $sprintColumnTask->column_id;
			
			// Change ordering in the previous column
			$previousColumnNextTask = SprintColumnTask::model()->findByAttributes(
				array(
					'previous_id' => $sprintColumnTask->task->id,
					'sprint_id' => $sprintId,
					'column_id' => $fromColumnId
					)
				);
			if($previousColumnNextTask !== null)
			{
				//echo $sprintColumnTask->previous_id;
				$previousColumnNextTask->previous_id = $sprintColumnTask->previous_id;
				$previousColumnNextTask->save();
			}
			
			// Change ordering in the new column
			$newColumnNextTask = SprintColumnTask::model()->findByAttributes(
				array(
					'previous_id' => $previousId,
					'sprint_id' => $sprintId,
					'column_id' => $toColumnId
					)
				);
			if($newColumnNextTask !== null)
			{
				$newColumnNextTask->previous_id = $sprintColumnTask->task->id;
				$newColumnNextTask->save();
			}
			
			// Update
			$sprintColumnTask->column_id = $toColumnId;
			$sprintColumnTask->previous_id = $previousId;
			if(!$sprintColumnTask->save())
			{
				throw new CException('Can not move task to another column.');
			}
			
			// Log the moving
			$sprintTaskMove = new SprintTaskMove;
			$sprintTaskMove->sprint_id = $sprintId;
			$sprintTaskMove->task_id = $taskId;
			$sprintTaskMove->from_column_id = $fromColumnId;
			$sprintTaskMove->to_column_id = $toColumnId;
			if(!$sprintTaskMove->save())
			{
				throw new CException('Can not log the task moving to another column.');
			}
			
			$transaction->commit();
			
			$success = true;
		}
		catch(Exception $e)
		{
			$transaction->rollBack();
			
			$success = false;
		}
		
		$this->sendJsonResponse($success, 'There was an error moving the task.');
	}
	
	/**
	 * Move a task from inside its own column - change its position
	 * @param $projectId int id of the project
	 * @param sprintId int id of the sprint
	 */
	public function actionRearrangeColumnTask($projectId, $sprintId)
	{
		$taskId = $this->getPostDataSafe('taskId');
		$previousId = $this->getPostDataSafe('previousId');
		
		$task = $this->getTaskAndValidateInputData($projectId, $sprintId, $taskId);
		
		$success = false;
		
		$transaction = Yii::app()->db->beginTransaction();
		try
		{
			// Find the entry
			$sprintColumnTask = $task->sprintColumnTasks[0];
			
			$columnId = $sprintColumnTask->column_id;
			
			// Change ordering at the previous place of the task
			$previousNextTask = SprintColumnTask::model()->findByAttributes(
				array(
					'previous_id' => $sprintColumnTask->task->id,
					'sprint_id' => $sprintId,
					'column_id' => $columnId
					)
				);
			if($previousNextTask !== null)
			{
				$previousNextTask->previous_id = $sprintColumnTask->previous_id;
				$previousNextTask->save();
			}
			
			// Change ordering at the new place of the task
			$newNextTask = SprintColumnTask::model()->findByAttributes(
				array(
					'previous_id' => $previousId,
					'sprint_id' => $sprintId,
					'column_id' => $columnId
					)
				);
			if($newNextTask !== null)
			{
				$newNextTask->previous_id = $sprintColumnTask->task->id;
				$newNextTask->save();
			}
			
			// Update
			$sprintColumnTask->previous_id = $previousId;
			if(!$sprintColumnTask->save())
			{
				throw new CException('Can not move task to another column.');
			}
			
			$transaction->commit();
			
			$success = true;
		}
		catch(Exception $e)
		{
			$transaction->rollBack();
			
			$success = false;
		}
		
		$this->sendJsonResponse($success, 'There was an error rearranging the task.');
	}
	
	/**
	 * Assign the current user to a task
	 * @param $projectId int id of the project
	 * @param sprintId int id of the sprint
	 */
	public function actionAssign($projectId, $sprintId)
	{
		$taskId = $this->getPostDataSafe('taskId');
		
		$success = false;
		
		$sprintTask = SprintTask::model()->findByAttributes(
			array(
				'sprint_id' => $sprintId,
				'task_id' => $taskId,
				)
			);
		if($sprintTask === null)
		{
			throw new CHttpException(403);
		}
		
		$sprintTaskAssignment = new SprintTaskAssignment;
		$sprintTaskAssignment->sprint_task_id = $sprintTask->id;
		$sprintTaskAssignment->user_id = Yii::app()->user->getId();
		$success = $sprintTaskAssignment->save();
		
		$this->sendJsonResponse($success, 'There was an error assigning yourself to the task.');
	}
	
	/**
	 * Unassign the current user to a task
	 * @param $projectId int id of the project
	 * @param sprintId int id of the sprint
	 */
	public function actionUnassign($projectId, $sprintId)
	{
		$taskId = $this->getPostDataSafe('taskId');
		
		$success = false;
		
		$criteria = new CDbCriteria;
		$criteria->alias = 'sta';
		$criteria->join = 'LEFT JOIN sprint_task as st ON sta.sprint_task_id = st.id';
		$criteria->condition = 'st.sprint_id = :sprintId AND st.task_id = :taskId AND sta.user_id = :userId';
		$criteria->params = array(
			':sprintId' => $sprintId,
			':taskId' => $taskId,
			':userId' => Yii::app()->user->getId()
			);
		
		$sprintTaskAssignment = SprintTaskAssignment::model()->find($criteria);
		if($sprintTaskAssignment === null)
		{
			throw new CHttpException(403);
		}
		
		$success = $sprintTaskAssignment->delete();
		
		$this->sendJsonResponse($success, 'There was an error unassigning yourself from the task.');
	}
	
	/**
	 * Render the list of tasks for a column
	 * @param sprintId int id of the sprint
	 */
	public function actionColumnTaskList($projectId, $sprintId, $columnId)
	{
		$project = $this->getProject($projectId, true);
		$sprint = $this->getSprintSafe($sprintId, $projectId);
		$column = $this->getColumnSafe($columnId, $project);
		
		$columnArranger = new ColumnArranger;
		$columns = $columnArranger->getArrangedColumns($projectId);
		
		$columnTasks = SprintColumnTask::model()->findAllByAttributes(
			array('sprint_id' => $sprintId, 'column_id' => $column->id)
			);
		
		$taskStoryPoints = TaskStoryPointsCalculator::calculate($sprintId, $columns);
		
		$taskAssignees = $this->getTaskAssignees($sprintId);
		
		$currentUser = User::model()->findByPk(Yii::app()->user->getId());
		$currentUserName = $currentUser->username;
		if($currentUser->name !== null && !empty($currentUser->name))
		{
			$currentUserName = $currentUser->name;
		}
		
		$this->renderPartial(
			'columnTaskList',
			array(
				'projectId' => $projectId,
				'sprint' => $sprint,
				'columnTasks' => $columnTasks,
				'taskStoryPoints' => $taskStoryPoints,
				'taskAssignees' => $taskAssignees,
				'currentUserName' => $currentUserName,
				)
			);
	}
	
	/**
	 * Get task and verify the input data for moving a task.
	 * Verifies the task's validity.
	 * Redirects the user to the main page if the input data is not verified.
	 * @param sprintId int id of the sprint
	 * @param taskId int id of the task
	 * @param toColumnId int id of the column that the task is moved to,
	 * null if the task is moved to the same column
	 * @return Task the task
	 */
	private function getTaskAndValidateInputData($projectId, $sprintId, $taskId, $fromColumnId = null, $toColumnId = null)
	{
		if($toColumnId !== null)
		{
			if((int)$toColumnId !== 1
				&& (int)$toColumnId !== 2

ScrumTool/protected/controllers/TaskController.php
<?php

Yii::import('application.models.task.*');

class TaskController extends Controller
{
	/**
	 * Filters
	 */
	public function filters()
	{
		return array(
			'accessControl',
			array('application.filters.HasProjectFilter'),
		);
	}
	
	/**
	 * Access rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',
				'actions' => array('taskList', 'view'),
				'users' => array('@'),
			),
			array('allow',
				'actions' => array('add', 'edit', 'delete'),
				'roles' => array('scrum_master'),
			),
			array('deny',
				'users' => array('?'),
			),
			array('deny',
				'users' => array('*'),
			),
		);
	}
	
	/**
	 * View a task
	 */
	public function actionView($projectId, $storyId, $taskId)
	{
		$story = Story::model()->findByPk(
			$storyId,
			'project_id = :projectId',
			array(':projectId' => $projectId)
			);
		$this->verifyStory($story);
		
		$task = Task::model()->findByPk(
			$taskId,
			'story_id = :storyId',
			array(':storyId' => $storyId)
			);
		$this->verifyTask($task);
		
		$this->renderPartial(
			'view',
			array(
				'story' => $story,
				'task' => $task,
				)
			);
	}
	
	/**
	 * Add a task to a story
	 */
	public function actionAdd($projectId, $storyId)
	{
		$story = Story::model()->findByPk(
			$storyId,
			'project_id = :projectId', array(':projectId' => $projectId)
			);
		$this->verifyStory($story);
		
		$taskForm = new TaskForm($storyId);
		
		$this->performAjaxValidation('task-form', $taskForm);
		
		if(isset($_POST['TaskForm']))
		{
			$success = false;
			
			$taskForm->attributes = $_POST['TaskForm'];
			$taskForm->purify();
			if($taskForm->validate())
			{
				// Create the task
				$task = new Task;
				$task->name = $taskForm->name;
				$task->story_id = $storyId;
				if($taskForm->description !== null)
				{
					$task->description = $taskForm->description;
				}
				$task->estimation = $taskForm->estimation;
				$success = $task->save();
			}
			
			$this->formResponse(
				$success,
				'task-submit',
				$taskForm,
				$this->createUrl('backlog/index')
				);
		}
		
		$this->displayForm('task-render', 'add', $taskForm);
	}
	
	/**
	 * Edit story
	 */
	public function actionEdit($projectId, $storyId, $taskId)
	{
		$story = Story::model()->findByPk(
			$storyId,
			'project_id = :projectId',
			array(':projectId' => $projectId)
			);
		$this->verifyStory($story);
		
		$task = Task::model()->findByPk(
			$taskId,
			'story_id = :storyId',
			array(':storyId' => $storyId)
			);
		$this->verifyTask($task);
		
		$taskForm = new TaskForm($storyId, $taskId);
		$taskForm->name = $this->purify($task->name);
		$taskForm->description = $this->purify($task->description);
		$taskForm->estimation = $this->purify($task->estimation);
		
		$this->performAjaxValidation('task-form', $taskForm);
		
		if(isset($_POST['TaskForm']))
		{
			$success = false;
			
			$taskForm->attributes = $_POST['TaskForm'];
			$taskForm->purify();
			if($taskForm->validate())
			{
				$task->name = $taskForm->name;
				$task->description = $taskForm->description;
				$task->estimation = $taskForm->estimation;
				
				$success = $task->save();
			}
			
			$this->formResponse(
				$success,
				'task-submit',
				$taskForm,
				$this->createUrl('backlog/index')
				);
		}
		
		$this->displayForm('task-render', 'edit', $taskForm);
	}
	
	/**
	 * Delete story
	 */
	public function actionDelete($projectId, $storyId, $taskId)
	{
		$story = Story::model()->findByPk(
			$storyId,
			'project_id = :projectId',
			array(':projectId' => $projectId)
			);
		$this->verifyStory($story);
		
		$task = Task::model()->findByPk(
			$taskId,
			'story_id = :storyId',
			array(':storyId' => $storyId)
			);
		$this->verifyTask($task);
		
		$success = $task->delete();
		
		$this->sendJsonResponse(
			$success,
			'There was an error archiving the task.'
			);
	}
	
	/**
	 * Verifies that a task is not null.
	 * If the task is null, sends an appropriate json message and ends.
	 * @param Task the Task
	 */
	private function verifyTask($task)
	{
		if($task === null)
		{
			$this->sendJsonResponse(
				false,
				'There is no such task in this story.'
				);
			
			Yii::app()->end();
		}
	}
}

ScrumTool/protected/views/board/columnTaskList.php
<?php if($columnTasks !== null): ?>
	<?php foreach($columnTasks as $columnTask): ?>
		<?php $task = $columnTask->task; ?>
		<div id="task_<?php echo $task->id; ?>" class="task">
			<div class="task-title">
				<span><?php echo $task->name; ?></span>
			</div>
			<div class="task-estimation">
				<span>
					<?php 
						if(isset($taskStoryPoints[$task->id]))
						{
							echo $taskStoryPoints[$task->id];
						}
						else
						{
							echo '0';
						}
					?>
					/ <?php echo $task->estimation; ?>
				</span>
			</div>
			<br style="clear: both;" />
			<div class="task-actions">
				<span><a href="<?php echo $this->createUrl('task/view', array('projectId' => $projectId, 'storyId' => $task->story->id, 'taskId' => $task->id)); ?>" class="btnViewTask"><?php echo Yii::t('general', 'view'); ?></a></span>
				<?php if(isset($taskAssignees[$task->id]) && in_array($currentUserName, $taskAssignees[$task->id])): ?>
					<span><a href="<?php echo $this->createUrl('board/unassign', array('projectId' => $projectId, 'sprintId' => $sprint->id)); ?>" class="btnUnassign"><?php echo Yii::t('board', 'unassign me'); ?></a></span>
				<?php else: ?>
					<span><a href="<?php echo $this->createUrl('board/assign', array('projectId' => $projectId, 'sprintId' => $sprint->id)); ?>" class="btnAssign"><?php echo Yii::t('board', 'assign me'); ?></a></span>
				<?php endif; ?>
			</div>
			<div class="task-assignees">
				<span>
					<?php if(isset($taskAssignees[$task->id])): ?>
						<?php foreach($taskAssignees[$task->id] as $i => $assignee): ?>
							<?php if($i !== 0): ?>
								<?php echo ', '; ?>
							<?php endif; ?>
							
							<?php echo $assignee; ?>
						<?php endforeach; ?>
					<?php else: ?>
						<?php echo Yii::t('board', 'Not assigned'); ?>
					<?php endif; ?>	
				</span>
			</div>
			<br style="clear: both;" />
		</div>
	<?php endforeach; ?>
<?php endif; ?>

ScrumTool/protected/views/board/index.php
<?php
$this->pageTitle = Yii::app()->name . ' - ' . Yii::t('board', '{sprint} board', array('{sprint}' => $sprint->name));
?>

<div class="centered-div sprint-board">

	<div class="sprint-board-title">
		<span><?php echo Yii::t('board', '{sprint} board', array('{sprint}' => $sprint->name)); ?></span>
	</div>
	
	<div class="board">
		<table>
			<tr>
				<?php $columnWidthPercent = 100 / count($columns); ?>
				<?php foreach($columns as $column): ?>
					<th style="width: <?php echo $columnWidthPercent; ?>%;"><?php echo Yii::t('columns', $column->name); ?></th>
				<?php endforeach; ?>
			</tr>
			<tr>
				<?php foreach($columns as $column): ?>
					<td>
						<div id="column_<?php echo $column->id; ?>" class="column">
							<?php $columnTasks = $sprintColumnTasks[$column->id]; ?>
							<?php $this->renderPartial('columnTaskList', array('projectId' => $projectId, 'sprint' => $sprint, 'columnTasks' => $columnTasks, 'taskStoryPoints' => $taskStoryPoints, 'taskAssignees' => $taskAssignees, 'currentUserName' => $currentUserName)); ?>
						</div>
					</td>
				<?php endforeach; ?>
			</tr>
		</table>
	</div>
	
	<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/assets/javascript/jquery-ui/jquery-ui.min.js"></script>
	<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/assets/javascript/common.js"></script>
	<script type="text/javascript" src="<?php echo Yii::app()->request->baseUrl; ?>/assets/javascript/infoDialog.js"></script>
	<script type="text/javascript">
	/*<![CDATA[*/
		jQuery(document).ready(function()
		{
			jQuery('.btnViewTask').live('click', function()
			{
				var settings =
				{
					'contentUrl': jQuery(this).attr('href'),
					'title': 'View task',
				};
				
				return createInfoDialog(settings);
			});
			
			/**
			 * Load the list of tasks for a column
			 * @param columnId string the element id of the column on the page
			 */
			function loadColumn(columnId)
			{
				var url = createUrl('<?php echo $this->createUrl('board/columnTaskList', array('projectId' => $projectId, 'sprintId' => $sprint->id)); ?>', {columnId: columnId});
				var column = jQuery('#column_' + columnId);
				column.load(url);
			}
			
			// Variables used to track the state of the task dragging
			var oldList;	// Set when sorting starts
			var newList;	// Set on every change
			var item;		// The item being dragged
			jQuery('.column').sortable(
			{
				'containment': 'document',
				'connectWith': '.column',
				'scroll': false,
				'tollerance': 'pointer',
				'placeholder': 'placeholder',
				'forcePlaceholderSize': true,
				'cursor': 'move',
				'start': function(event, ui)
				{
					item = ui.item;
					newList = oldList = ui.item.parent();
				},
				'change': function(event, ui)
				{
					if(ui.sender !== null)
					{
						newList = ui.placeholder.parent();
					}
				},
				'stop': function(event, ui)
				{
					var senderList = jQuery(oldList);
					var senderListItemIds = senderList.sortable('toArray');
					var receiverList = jQuery(newList);
					var receiverListItemIds = receiverList.sortable('toArray');
					
					var index = item.index();
					var previousId = -1;
					
					if(index > 0)
					{
						previousId = getTaskId(receiverListItemIds[index - 1]);
					}
					
					if(senderList.attr('id') === receiverList.attr('id'))
					{
						// The move is in the same column
						var data =
						{
							taskId: getTaskId(receiverListItemIds[index]),
							previousId: previousId,
						};
						
						jQuery.ajax(
						{
							type: 'POST',
							url: createUrl('<?php echo $this->createUrl('board/rearrangeColumnTask', array('projectId' => $projectId, 'sprintId' => $sprint->id)); ?>'),
							data: data,
							dataType: 'json',
							success: function(data)
							{
								//loadColumn(receiverColumnId);
							}
						});
					}
					else
					{
						// The move is from one column to another
						var senderColumnId = getColumnId(senderList.attr('id'));
						var receiverColumnId = getColumnId(receiverList.attr('id'));
						
						var data =
						{
							taskId: getTaskId(receiverListItemIds[index]),
							fromColumnId: senderColumnId,
							toColumnId: receiverColumnId,
							previousId: previousId,
						};
						
						jQuery.ajax(
						{
							type: 'POST',
							url: createUrl('<?php echo $this->createUrl('board/move', array('projectId' => $projectId, 'sprintId' => $sprint->id)); ?>'),
							data: data,
							dataType: 'json',
							success: function(data)
							{
								//loadColumn(senderColumnId);
								//loadColumn(receiverColumnId);
							}
						});
					}
					
					// Log some stuff
					/*
					console.log(event);
					console.log(ui);
					console.log('index in array: ' + item.index());
					console.log('sender column id: ' + senderList.attr('id'));
					
					console.log('receiver column id: ' + receiverList.attr('id'));
					
					var id = receiverList.sortable('toArray')[item.index()];
					console.log('task id: ' + id);
					
					console.log('previous id: ' + previousId);
					
					console.log('sender list: ' + senderList.sortable('toArray'));
					console.log('receiver list: ' + receiverList.sortable('toArray'));
					*/
				},
			});
			
			/**
			 * Implements the assignment and unassigment of tasks
			 * @param jQueryObj jQuery object of the button that was clicked
			 */
			function assignmentImpl(jQueryObj)
			{
				var url = jQueryObj.attr('href');
				
				var task = jQueryObj.parents('.task');
				var taskId = getTaskId(task.attr('id'));
				
				var column = jQueryObj.parents('.column');
				var columnId = getColumnId(column.attr('id'));
				
				var data =
				{
					taskId: taskId
				};
				
				jQuery.ajax(
				{
					type: 'POST',
					url: url,
					data: data,
					dataType: 'json',
					success: function(data)
					{
						loadColumn(columnId);
					}
				});
				
				return false;
			}
			
			jQuery('.btnAssign').live('click', function()
			{
				return assignmentImpl(jQuery(this));
			});
			
			jQuery('.btnUnassign').live('click', function()
			{
				return assignmentImpl(jQuery(this));
			});
			
			/**
			 * Get the id of the task by its element id.
			 */
			function getTaskId(elementId)
			{
				return stripPrefix('task_', elementId);
			}
			
			/**
			 * Get the id of the column by its element id.
			 */
			function getColumnId(elementId)
			{
				return stripPrefix('column_', elementId);
			}
		});
	/*]]>*/
	</script>
	
</div><!-- sprint-board -->